package com.clps.entity;
// Generated 2018-1-12 12:52:51 by Hibernate Tools 5.2.6.Final

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private String catid;
	private String name;
	private String descn;

	public Category() {
	}

	public Category(String catid) {
		this.catid = catid;
	}

	public Category(String catid, String name, String descn) {
		this.catid = catid;
		this.name = name;
		this.descn = descn;
	}

	public String getCatid() {
		return this.catid;
	}

	public void setCatid(String catid) {
		this.catid = catid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescn() {
		return this.descn;
	}

	public void setDescn(String descn) {
		this.descn = descn;
	}

}
