package com.clps.entity;
// Generated 2018-1-12 12:52:51 by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;

/**
 * Lineitem generated by hbm2java
 */
public class Lineitem implements java.io.Serializable {

	private LineitemId id;
	private String itemid;
	private int quantity;
	private BigDecimal unitprice;

	public Lineitem() {
	}
	public Lineitem(LineitemId id, String itemid, int quantity, BigDecimal unitprice) {
		this.id = id;
		this.itemid = itemid;
		this.quantity = quantity;
		this.unitprice = unitprice;
	}

	@Override
	public String toString() {
		return "Lineitem [id=" + id + ", itemid=" + itemid + ", quantity=" + quantity + ", unitprice=" + unitprice
				+ "]";
	}
	public LineitemId getId() {
		return this.id;
	}

	public void setId(LineitemId id) {
		this.id = id;
	}

	public String getItemid() {
		return this.itemid;
	}

	public void setItemid(String itemid) {
		this.itemid = itemid;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public BigDecimal getUnitprice() {
		return this.unitprice;
	}

	public void setUnitprice(BigDecimal unitprice) {
		this.unitprice = unitprice;
	}

}
