package com.clps.entity;
// Generated 2018-1-12 12:52:51 by Hibernate Tools 5.2.6.Final

import java.sql.Timestamp;
import java.util.Date;

/**
 * Orderstatus generated by hbm2java
 */
public class Orderstatus implements java.io.Serializable {

	private OrderstatusId id;
	private Timestamp timestamp;
	private String status;

	public Orderstatus() {
	}

	public Orderstatus(OrderstatusId id, String status) {
		this.id = id;
		this.status = status;
	}

	public OrderstatusId getId() {
		return this.id;
	}

	public void setId(OrderstatusId id) {
		this.id = id;
	}

	public Timestamp getTimestamp() {
		return timestamp;
	}

	public void setTimestamp(Timestamp timestamp) {
		this.timestamp = timestamp;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
