package com.clps.entity;
// Generated 2018-1-12 12:52:51 by Hibernate Tools 5.2.6.Final

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private String productid;
	private String category;
	private String name;
	private String descn;

	public Product() {
	}

	public Product(String productid, String category) {
		this.productid = productid;
		this.category = category;
	}

	public Product(String productid, String category, String name, String descn) {
		this.productid = productid;
		this.category = category;
		this.name = name;
		this.descn = descn;
	}

	public String getProductid() {
		return this.productid;
	}

	public void setProductid(String productid) {
		this.productid = productid;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescn() {
		return this.descn;
	}

	public void setDescn(String descn) {
		this.descn = descn;
	}

}
