package com.clps.entity;
// Generated 2018-1-12 12:52:51 by Hibernate Tools 5.2.6.Final

/**
 * Profile generated by hbm2java
 */
public class Profile implements java.io.Serializable {

	private String userid;
	private String langpref;
	private String favcategory;
	private Integer mylistopt;
	private Integer banneropt;

	public Profile() {
	}

	public Profile(String userid, String langpref) {
		this.userid = userid;
		this.langpref = langpref;
	}

	public Profile(String userid, String langpref, String favcategory, Integer mylistopt, Integer banneropt) {
		this.userid = userid;
		this.langpref = langpref;
		this.favcategory = favcategory;
		this.mylistopt = mylistopt;
		this.banneropt = banneropt;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getLangpref() {
		return this.langpref;
	}

	public void setLangpref(String langpref) {
		this.langpref = langpref;
	}

	public String getFavcategory() {
		return this.favcategory;
	}

	public void setFavcategory(String favcategory) {
		this.favcategory = favcategory;
	}

	public Integer getMylistopt() {
		return this.mylistopt;
	}

	public void setMylistopt(Integer mylistopt) {
		this.mylistopt = mylistopt;
	}

	public Integer getBanneropt() {
		return this.banneropt;
	}

	public void setBanneropt(Integer banneropt) {
		this.banneropt = banneropt;
	}

}
